#! /bin/dash

sudo apt-get update -y

sudo apt-get install -y synaptic
sudo apt-get install -y htop

#### pynetkey  ##################################################################

sudo apt-get install -y python-appindicator
#sudo apt-get install libgnome2-bin
#gnome-open ~/Prog/pynetkey20120905.deb

#### java  ######################################################################


sudo mkdir /opt/jdk
sudo tar -zxf /home/murray/prog/java/jdk*.tar.gz -C /opt/jdk
ls /opt/jdk
sudo update-alternatives --install /usr/bin/java java /opt/jdk/jdk*/bin/java 100
sudo update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk*/bin/javac 100
java -version
javac -version


#### alternative method: #####

#sudo apt-add-repository ppa:webupd8team/java
#sudo apt-get update
#sudo apt-get install oracle-java8-installer
## sudo apt-get install eclipse #necessary?

#### eclipse ####################################################################

sudo tar -zxvf /home/murray/prog/Eclipsedownloads/eclipse*.tar.gz -C /opt


# put this in a file named eclipse.desktop

cat > eclipse.desktop << "EOF"
[Desktop Entry]
Name=Eclipse 
Type=Application
Exec=env UBUNTU_MENUPROXY=0 eclipse
Terminal=false
Icon=eclipse
Comment=Integrated Development Environment
NoDisplay=false
Categories=Development;IDE;
Name[en]=Eclipse
EOF

sudo desktop-file-install eclipse.desktop
sudo ln -s /opt/eclipse/eclipse /usr/local/bin/eclipse
sudo cp /opt/eclipse/icon.xpm /usr/share/pixmaps/eclipse.xpm

#sudo chown -R $USER:$USER /opt/eclipse/configuration/org.eclipse.osgi ????

#### programming ################################################################

sudo apt-get install -y vim-gtk
sudo apt-get install -y make
cd ~/prog
tar -xjvf valgrind-3.13.0.tar.bz2
cd valgrind-3.13.0
./configure
make
sudo make install

sudo apt-get install -y git
sudo apt-get install -y gitg
sudo apt-get install -y gitk

sudo apt-get install -y nasm
sudo apt-get install -y libc6-dev-i386
sudo apt-get install -y libc6-dbg:i386 #???

sudo apt-get install -y python-matplotlib

sudo apt-get install -y libopenmpi-dev
sudo apt-get install -y openmpi-bin

#sudo apt-get install nodejs
#sudo apt-get install nodejs-legacy
#sudo apt-get install npm
#sudo npm install http-server -g
#sudo npm install express

##### multimedia ################################################################

sudo apt-get install -y chromium-browser
sudo apt-get install -y vlc
sudo apt-get install -y audacity
sudo apt-get install -y audacious
sudo apt-get install -y gimp
sudo apt-get install -y ubuntu-restricted-extras
sudo apt-get install -y steam
sudo apt-get install -y wine1.6 ### be warned! this is a large download!###
#sudo apt-get install -y texlive-full ### if you thought wine was big... ###

#### window management ##########################################################

sudo apt-get install -y gnome-session-flashback
#sudo apt-get install compiz
#sudo apt-get install compizconfig-settings-manager
#sudo apt-get install compiz-plugins-extra
sudo apt-get install -y xfce4

# xinput --list
# xinput disable <touchscreen id>

